language: python
services:
  - docker
python:
  - "3.8"
install:
  - make deps
script:
  - make test
  - make lint
  - make docker_build
  - make docker_push
#linter:
#  - make lint
#script:
#  - make test
#after_success:
#  - make docker_build
