language: python
services:
  - docker
python:
  - "3.8"
install:
  - make deps
script:
  - make test
  - make lint
  - make docker_build
  - make docker_push
deploy:
  provider: heroku
  app: fast-sierra-68064
  api_key: ${HEROKU_API_KEY}
#linter:
#  - make lint
#script:
#  - make test
#after_success:
#  - make docker_build
